### ISSUE TITLE
S1 App的官方微信群

### ISSUE THREAD

**Issue by pgain2004** [succlz123/S1-Go#1]
你好，Mufasa开了个S1 App微信群，方便第三方客户端作者交流和更新，提供一些新接口和技术支援。推荐加一下哦。
二维码：http://wx1.sinaimg.cn/large/73508f0fgy1fek3bluqbyj20da0i440m.jpg

**Comment by succlz123** [comment]
才看到呀 二维码好像过期了 😃

**Comment by pgain2004** [comment]
或者先加一下Q群？表情包等资源都在里面，几位老爷和官方开发者也在。
338163318
